### ISSUE TITLE
PIONS_LOG_DISABLED

### ISSUE THREAD

**Issue by enobufs** [pion/logging#7]
## Summary
Provide a way to disable logging completely.

## Motivation
Default logging is currently set to ERROR. In order to disable logging completely, we need to use API to configure a custom logger factory.

## Describe alternatives you've considered
Set the default logging level to "disabled"

If we were to keep the default logging level as Error and allow users to use env vars by default, then we should provide a way to disable the logging completely with the env var.

```
diff --git a/logger.go b/logger.go
index d3c0156..3e07cdd 100644
--- a/logger.go
+++ b/logger.go
@@ -181,11 +181,12 @@ func NewDefaultLoggerFactory() *DefaultLoggerFactory {
        factory.Writer = os.Stdout

        logLevels := map[string]LogLevel{
-               "ERROR": LogLevelError,
-               "WARN":  LogLevelWarn,
-               "INFO":  LogLevelInfo,
-               "DEBUG": LogLevelDebug,
-               "TRACE": LogLevelTrace,
+               "DISABLED": LogLevelDisabled,
+               "ERROR":    LogLevelError,
+               "WARN":     LogLevelWarn,
+               "INFO":     LogLevelInfo,
+               "DEBUG":    LogLevelDebug,
+               "TRACE":    LogLevelTrace,
        }

        for name, level := range logLevels {
```

~~Ideally, we should set the default level to "Disabled" IMO.~~ (keep the current default)

**Comment by justinokamoto** [comment]
Hello, just starting on Pion so looking for low hanging fruit to close out :) I plan to go with your alternative solution to allow disabling logs using env var.

**Comment by enobufs** [comment]
@Sean-Der @hugoArregui Any thoughts on this issue? Allowing disabling loggin by an envvar won't hurt us, and it is especially easier for people who have not used webrtc.API (to access SettingEngine).

**Comment by Sean-Der** [comment]
@enobufs 👍 from me!

I vote for keeping the default level as it is. Most people are just doing a `PeerConnection` from the examples so nice to keep a low barrier of entry :)

**Comment by Sean-Der** [comment]
@justinokamoto Would you mind also support `PION_` instead of `PIONS_` since we renamed.

We should keep the support for `PIONS_` still, but will stop publishing that in our documentation.

**Comment by justinokamoto** [comment]
@Sean-Der Sounds good!
